accounting/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'accounts/',include('accountingApp.urls')),
]

accountingApp/urls.py
from django.conf.urls import url
from . import views

app_name='accountingApp'

urlpatterns=[
    url(r'^$',views.Index.as_view(), name='index'),
    url(r'^invoice/$',views.Invoice.as_view(), name='invoice'),
    url(r'^inventory/$',views.Inventory.as_view(), name='inventory'),
    url(r'^dashboard/orders/$',views.Dashboard.as_view(), name='dashboard'),
    url(r'^dashboard/items/$',views.Items.as_view(), name='items'),
    url(r'^dashboard/analytics/$',views.Analytics.as_view(), name='analytics'),
    url(r'^customers/$',views.Customers.as_view(), name='customers'),
    url(r'^about/$',views.About.as_view(), name='about'),
]

accountingApp/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.

class Customer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,10}$', message="Phone number must be entered in the format: '+1234567890'. Up to 10 digits allowed")
    phone_number = models.CharField(validators=[phone_regex], blank=True, max_length=10)
    email = models.EmailField()
    billing_address = models.CharField(max_length=500)
    shipping_address = models.CharField(max_length=500)

class Item(models.Model):
    name = models.CharField(max_length=100)
    sku = models.CharField(max_length=10)
    retail_price = models.FloatField()
    selling_price = models.FloatField()
    color = models.CharField(max_length=10)
    new_item = models.BooleanField()

class Order(models.Model):
    customer = models.ForeignKey(Customer)
    order_date = models.DateField()
    order_status = models.CharField(max_length=20)
    total_price = models.FloatField()

class OrderItems(models.Model):
    order = models.ForeignKey(Order)
    item = models.ForeignKey(Item)
    quantity = models.IntegerField()

class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,10}$',
                                 message="Phone number must be entered in the format: '+9999999999'. Up to 10 digits allowed")
    phone_number = models.CharField(validators=[phone_regex], blank=True, max_length=10)
    email = models.EmailField()
    joining_date = models.DateField();
    salary = models.FloatField()
    role = models.CharField(max_length=50)

accountingApp/views.py
from django.shortcuts import render,redirect
from django.views.generic import View
from highcharts.views import HighChartsBarView

import random


# Create your views here.

class Index(View):

    template_name = 'accounting/home.html'

    def get(self, request):
        return render(request,self.template_name)

class Invoice(View):

    template_name = 'accounting/invoice.html'

    def get(self,request):
        return render(request, self.template_name)

class About(View):

    template_name = 'accounting/about.html'

    def get(self, request):
        return render(request,self.template_name)

class Inventory(View):

    template_name = 'accounting/inventory.html'

    def get(self, request):
        return render(request,self.template_name)

class Dashboard(View):
    template_name = 'accounting/dashboard/orders.html'

    def get(self, request):
        return render(request, self.template_name)

class Customers(View):
    template_name = 'accounting/customers.html'

    def get(self, request):
        return render(request, self.template_name)

class Items(View):
    template_name = 'accounting/dashboard/items.html'

    def get(self, request):
        return render(request, self.template_name)

class Analytics(View):
    template_name = 'accounting/dashboard/analytics.html'

    def get(self, request):
        return render(request, self.template_name)

'''
class BarView(HighChartsBarView):
    categories = ['Orange', 'Bananas', 'Apples']

    @property
    def series(self):
        result = []
        for name in ('Joe', 'Jack', 'William', 'Averell'):
            data = []
            for x in range(len(self.categories)):
                data.append(random.randint(0, 10))
            result.append({'name': name, "data": data})
        return result
'''

accountingApp/templates/accounting/Invoicecode.html
{% extends 'accounting/base.html' %}

{% block content %}

<br><br>
<div class="container">
    <div class="row">

        <div class="col-xs-12">
            <div class="text-xs-center">
                <h2>Invoice for purchase #33221</h2>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-12 col-md-3 col-lg-3 float-xs-left">
                    <div class="card height">
                        <div class="card-header">Billing Details</div>
                        <div class="card-block">
                            <strong>David Peere:</strong><br>
                            1111 Army Navy Drive<br>
                            Arlington<br>
                            VA<br>
                            <strong>22 203</strong><br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-3 col-lg-3">
                    <div class="card height">
                        <div class="card-header">Payment Information</div>
                        <div class="card-block">
                            <strong>Card Name:</strong> Visa<br>
                            <strong>Card Number:</strong> ***** 332<br>
                            <strong>Exp Date:</strong> 09/2020<br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-3 col-lg-3">
                    <div class="card height">
                        <div class="card-header">Order Preferences</div>
                        <div class="card-block">
                            <strong>Gift:</strong> No<br>
                            <strong>Express Delivery:</strong> Yes<br>
                            <strong>Insurance:</strong> No<br>
                            <strong>Coupon:</strong> No<br>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-3 col-lg-3 float-xs-right">
                    <div class="card height">
                        <div class="card-header">Shipping Address</div>
                        <div class="card-block">
                            <strong>David Peere:</strong><br>
                            1111 Army Navy Drive<br>
                            Arlington<br>
                            VA<br>
                            <strong>22 203</strong><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card ">
                <div class="card-header">
                    <h3 class="text-xs-center"><strong>Order summary</strong></h3>
                </div>
                <div class="card-block">
                    <div class="table-responsive">
                        <table class="table table-sm">
                            <thead>
                                <tr>
                                    <td><strong>Item Name</strong></td>
                                    <td class="text-xs-center"><strong>Item Price</strong></td>
                                    <td class="text-xs-center"><strong>Item Quantity</strong></td>
                                    <td class="text-xs-right"><strong>Total</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Samsung Galaxy S5</td>
                                    <td class="text-xs-center">$900</td>
                                    <td class="text-xs-center">1</td>
                                    <td class="text-xs-right">$900</td>
                                </tr>
                                <tr>
                                    <td>Samsung Galaxy S5 Extra Battery</td>
                                    <td class="text-xs-center">$30.00</td>
                                    <td class="text-xs-center">1</td>
                                    <td class="text-xs-right">$30.00</td>
                                </tr>
                                <tr>
                                    <td>Screen protector</td>
                                    <td class="text-xs-center">$7</td>
                                    <td class="text-xs-center">4</td>
                                    <td class="text-xs-right">$28</td>
                                </tr>
                                <tr>
                                    <td class="highrow"></td>
                                    <td class="highrow"></td>
                                    <td class="highrow text-xs-center"><strong>Subtotal</strong></td>
                                    <td class="highrow text-xs-right">$958.00</td>
                                </tr>
                                <tr>
                                    <td class="emptyrow"></td>
                                    <td class="emptyrow"></td>
                                    <td class="emptyrow text-xs-center"><strong>Shipping</strong></td>
                                    <td class="emptyrow text-xs-right">$20</td>
                                </tr>
                                <tr>
                                    <td class="emptyrow"><i class="fa fa-barcode iconbig"></i></td>
                                    <td class="emptyrow"></td>
                                    <td class="emptyrow text-xs-center"><strong>Total</strong></td>
                                    <td class="emptyrow text-xs-right">$978.00</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.height {
    min-height: 200px;
}

.icon {
    font-size: 47px;
    color: #5CB85C;
}

.iconbig {
    font-size: 77px;
    color: #5CB85C;
}

.table > tbody > tr > .emptyrow {
    border-top: none;
}

.table > thead > tr > .emptyrow {
    border-bottom: none;
}

.table > tbody > tr > .highrow {
    border-top: 3px solid;
}
</style>

{% endblock %}

accountingApp/templates/accounting/about.html
{% extends 'accounting/base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <p>ABOUT PAGE</p>
            </div>
        </div>
    </div>

{% endblock %}

accountingApp/templates/accounting/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Accounting</title>
    {% load staticfiles %}
    <script src="{% static 'accounting/js/jquery-3.1.1.slim.min.js' %}"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/highcharts/highcharts.js' %}"></script>
    <script type="text/javascript" src="{% static 'accounting/js/highcharts.js' %}"></script>
    <link rel="stylesheet" href="{% static 'accounting/css/bootstrap.min.css' %}" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'accounting/css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'accounting/css/Abdemanaf.css' %}">

    <style type="text/css">body, html {
  height:100%;
}

body {
    #padding-top: 70px;
}

/* workaround modal-open padding issue */
body.modal-open {
    padding-right:0 !important;
}

#sidebar {
   padding-left:0;
}

/*
 * Off Canvas at medium breakpoint
 * --------------------------------------------------
 */
@media screen and (max-width: 48em) {

  .row-offcanvas {
    position: relative;
    -webkit-transition: all 0.25s ease-out;
    -moz-transition: all 0.25s ease-out;
    transition: all 0.25s ease-out;
  }

  .row-offcanvas-left
  .sidebar-offcanvas {
    left: -33%;
  }

  .row-offcanvas-left.active {
    left: 33%;
    margin-left: -6px;
  }

  .sidebar-offcanvas {
    position: absolute;
    top: 0;
    width: 33%;
    height: 100%;
  }
}

/*
 * Off Canvas wider at sm breakpoint
 * --------------------------------------------------
 */
@media screen and (max-width: 34em) {
  .row-offcanvas-left
  .sidebar-offcanvas {
    left: -45%;
  }

  .row-offcanvas-left.active {
    left: 45%;
    margin-left: -6px;
  }

  .sidebar-offcanvas {
    width: 45%;
  }
}

.card {
    overflow:hidden;
}

.card-block .rotate {
    z-index: 8;
    float: right;
    height: 100%;
}

.card-block .rotate i {
    color: rgba(20, 20, 20, 0.15);
    position: absolute;
    left: 0;
    left: auto;
    right: -10px;
    bottom: 0;
    display: block;
    -webkit-transform: rotate(-44deg);
    -moz-transform: rotate(-44deg);
    -o-transform: rotate(-44deg);
    -ms-transform: rotate(-44deg);
    transform: rotate(-44deg);
}
</style>

    {% block head %}
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'accountingApp:index' %}">Accounting</a>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a id='home' class="nav-link" href="{% url 'accountingApp:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a id='dashboard' class="nav-link" href="{% url 'accountingApp:dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a id= 'invoice' class="nav-link" href="{% url 'accountingApp:invoice' %}">Invoice</a>
        </li>
        <li class="nav-item">
          <a id='inventory' class="nav-link" href="{% url 'accountingApp:inventory' %}">Inventory</a>
        </li>
        <li class="nav-item">
          <a id='customers' class="nav-link" href="{% url 'accountingApp:customers' %}">Customers</a>
        </li>
        <li class="nav-item">
          <a id='about' class="nav-link" href="{% url 'accountingApp:about' %}">About</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
  </nav>

{% block content %}
{% endblock %}
<!--<script>
    $(function() {
        $("a").on("click", function() {
        //var id = $("a.active").attr('id');
        //$("a.active").removeClass("active");
        //$(this).addClass("active");
        //var id2 = $("a.active").attr('id');
        //window.alert(id + " " + id2);
        });

    });
  </script>-->

    <script src="{% static 'accounting/js/tether.min.js' %}" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static 'accounting/js/bootstrap.min.js' %}" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="{% static 'accounting/js/IE10-viewport-bug-workaround.js' %}"></script>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>

</body>
</html>

accountingApp/templates/accounting/customers.html
{% extends 'accounting/base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <p>CUSTOMERS PAGE</p>
            </div>
        </div>
    </div>

{% endblock %}

accountingApp/templates/accounting/dashboard/analytics.html
{% extends 'accounting/base.html' %}

{% block content %}
<br>
{% load staticfiles %}
   <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accountingApp:dashboard' %}">Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accountingApp:items' %}">Items</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'accountingApp:analytics' %}">Analytics</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Export</a>
            </li>
          </ul>

          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Transactions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Employees</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Suppliers</a>
            </li>
          </ul>

        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            <div id="container_chart" style="height: 300px"></div>

        </main>
      </div>
   </div>
{% endblock %}

accountingApp/templates/accounting/dashboard/items.html
{% extends 'accounting/base.html' %}

{% block content %}
<br>
{% load staticfiles %}

<div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accountingApp:dashboard' %}">Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'accountingApp:items' %}">Items</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accountingApp:analytics' %}">Analytics</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Export</a>
            </li>
          </ul>

          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Transactions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Employees</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Suppliers</a>
            </li>
          </ul>

        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">

          <div class="dropdown float-right">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMonthButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Select a Month
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMonthButton">
              <a class="dropdown-item" href="#">January</a>
              <a class="dropdown-item" href="#">February</a>
              <a class="dropdown-item" href="#">March</a>
            </div>
          </div>

          <div class="dropdown float-right">

             <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownYearButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Select a Year
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownYearButton">
              <a class="dropdown-item" href="#">2017</a>
              <a class="dropdown-item" href="#">2018</a>
              <a class="dropdown-item" href="#">2019</a>
            </div>
          </div>
          <h1>Dashboard</h1>


          <section class="row text-center placeholders">

            <div class="col-md-12">

              <div class="card-deck">
                <div class="col-md-2 offset-md-2">
                    <div class="card card-inverse card-success">
                      <div class="card-block bg-success">
                        <h6 class="text-uppercase text-left">New Items</h6>
                        <h4 class="display-4 text-left">130</h4>
                      </div>
                    </div>
                </div>

                <div class="col-md-2 offset-md-1">
                    <div class="card card-inverse card-info">
                      <div class="card-block bg-info">
                        <h6 class="text-uppercase text-left">Old items</h6>
                        <h4 class="display-4 text-left">1400</h4>
                      </div>
                    </div>
                </div>

              </div>

            </div>
            <!--
            <div class="col-6 col-sm-4 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>Profit</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-4 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>Month Sale</h4>
              <span class="text-muted">Something else</span>
            </div>

            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          -->



          </section>

          <h2>Items</h2>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>SKU</th>
                  <th>Item Name</th>
                  <th>Retail Price</th>
                  <th>Selling Price</th>
                  <th>Color</th>
                  <th>Quantity</th>
                </tr>
              </thead>
              <tbody>
                <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12345</td>
                  <td>Screw</td>
                  <td>0.250</td>
                  <td>0.500</td>
                  <td>-</td>
                  <td>100</td>
                </tr>
                <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12378</td>
                  <td>Door Lock</td>
                  <td>8.00</td>
                  <td>10.00</td>
                  <td>Gold</td>
                  <td>4</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12900</td>
                  <td>Handle</td>
                  <td>2.00</td>
                  <td>3.00</td>
                  <td>Silver</td>
                  <td>50</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12345</td>
                  <td>Screw</td>
                  <td>0.250</td>
                  <td>0.500</td>
                  <td>-</td>
                  <td>100</td>
                </tr>
                <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12378</td>
                  <td>Door Lock</td>
                  <td>8.00</td>
                  <td>10.00</td>
                  <td>Gold</td>
                  <td>4</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12900</td>
                  <td>Handle</td>
                  <td>2.00</td>
                  <td>3.00</td>
                  <td>Silver</td>
                  <td>50</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12345</td>
                  <td>Screw</td>
                  <td>0.250</td>
                  <td>0.500</td>
                  <td>-</td>
                  <td>100</td>
                </tr>
                <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12378</td>
                  <td>Door Lock</td>
                  <td>8.00</td>
                  <td>10.00</td>
                  <td>Gold</td>
                  <td>4</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12900</td>
                  <td>Handle</td>
                  <td>2.00</td>
                  <td>3.00</td>
                  <td>Silver</td>
                  <td>50</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12345</td>
                  <td>Screw</td>
                  <td>0.250</td>
                  <td>0.500</td>
                  <td>-</td>
                  <td>100</td>
                </tr>
                <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12378</td>
                  <td>Door Lock</td>
                  <td>8.00</td>
                  <td>10.00</td>
                  <td>Gold</td>
                  <td>4</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12900</td>
                  <td>Handle</td>
                  <td>2.00</td>
                  <td>3.00</td>
                  <td>Silver</td>
                  <td>50</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12345</td>
                  <td>Screw</td>
                  <td>0.250</td>
                  <td>0.500</td>
                  <td>-</td>
                  <td>100</td>
                </tr>
                <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12378</td>
                  <td>Door Lock</td>
                  <td>8.00</td>
                  <td>10.00</td>
                  <td>Gold</td>
                  <td>4</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12900</td>
                  <td>Handle</td>
                  <td>2.00</td>
                  <td>3.00</td>
                  <td>Silver</td>
                  <td>50</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12345</td>
                  <td>Screw</td>
                  <td>0.250</td>
                  <td>0.500</td>
                  <td>-</td>
                  <td>100</td>
                </tr>
                <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12378</td>
                  <td>Door Lock</td>
                  <td>8.00</td>
                  <td>10.00</td>
                  <td>Gold</td>
                  <td>4</td>
                </tr>
              <tr onclick="window.document.location='#';" data-toggle="modal" style="cursor:pointer;">
                  <td>12900</td>
                  <td>Handle</td>
                  <td>2.00</td>
                  <td>3.00</td>
                  <td>Silver</td>
                  <td>50</td>
                </tr>



              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

{% endblock %}

accountingApp/templates/accounting/home.html
{% extends 'accounting/base.html' %}

{% block content %}
<br><br>
    <div class="container">

        <div class="card text-center">
          <div class="card-header">
            Montly Sale
          </div>
          <div class="card-block">
            <h4 class="card-title">Sale for Month of August</h4>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Yearly Sale</a>
          </div>
          <div class="card-footer text-muted">
            15 days
          </div>
        </div>
    </div>

<br><br>

<div class="container">

        <div class="card text-center">
          <div class="card-header">
            Montly Profit
          </div>
          <div class="card-block">
            <h4 class="card-title">Profit for Month of August</h4>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Yearly Profit</a>
          </div>
          <div class="card-footer text-muted">
            15 days
          </div>
        </div>
    </div>

{% endblock %}